# Overrides for PROD: ingress hostnames (base values + this file used in Jenkins deploy)
global:
  baseKeycloakHost: auth.prod.local

keycloak:
  ingress:
    hostname: auth.prod.local
  extraEnvVars:
    - name: KC_HOSTNAME
      value: "http://auth.prod.local"
    - name: KC_HOSTNAME_STRICT_HTTPS
      value: "false"
    - name: KC_HTTP_ENABLED
      value: "true"

gateway-service:
  ingress:
    enabled: true
    hosts:
      - host: gateway.prod.local
        paths:
          - path: /
            pathType: Prefix
  frontService:
    url: http://front.prod.local

front-service:
  ingress:
    enabled: true
    hosts:
      - host: front.prod.local
        paths:
          - path: /
            pathType: Prefix
rabbitmq:
  ingress:
    enabled: true
    hostname: rabbitmq.prod.local