{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logstash.fullname" . }}
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
{{- end }}