apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifications-service.fullname" . }}-config
  labels:
    {{- include "notifications-service.labels" . | nindent 4 }}
data:
  application.yml: |
    server:
      port: {{ .Values.service.port }}
    spring:
      application:
        name: notifications-service
      cloud:
        config:
          enabled: false
        discovery:
          enabled: false
        eureka:
          client:
            enabled: false
      datasource:
        url: jdbc:postgresql://{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.auth.database }}
        username: {{ .Values.postgresql.auth.username }}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            default_schema: {{ .Values.config.database.schema }}
      liquibase:
        change-log: classpath:db/liquibase-changelog.xml
        clear-checksums: true
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://{{ .Values.global.baseKeycloakHost }}/realms/bank
      kafka:
        bootstrap-servers: {{ .Values.global.kafkaBootstrapServers }}
        consumer:
          group-id: notifications-service
          auto-offset-reset: earliest
          enable-auto-commit: false
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: "*"
    bank:
      notifications:
        kafka:
          topic: bank.notifications
          dlt-topic: bank.notifications.dlt
    management:
      endpoints:
        web:
          exposure:
            include: health, info
      endpoint:
        health:
          access: read-only