replicaCount: 1

image:
  repository: docker.elastic.co/logstash/logstash
  tag: "8.15.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 5044
  apiPort: 9600

elasticsearchHost: "elasticsearch"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: logstash.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

resources:
  requests: { memory: 256Mi, cpu: 100m }
  limits: { memory: 512Mi, cpu: 500m }