server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
          fail-on-error: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094,localhost:9095}

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh, health, info
  endpoint:
    refresh:
      access: unrestricted
    busrefresh:
      access: unrestricted
    health:
      access: read-only

logging:
  level:
    org.springframework.cloud.config: DEBUG