apiVersion: v1
kind: Secret
metadata:
  name: {{ include "account-service.fullname" . }}-secret
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  OAUTH_CLIENT_SECRET: {{ .Values.config.oauth.clientSecret | quote }}